### ISSUE TITLE
请问怎么把jdk8的版本给删了啊？

### ISSUE THREAD

**Issue by wyy0117** [gvcgo/vsources#2]
请问怎么把jdk8的版本给删了啊？

**Comment by moqsien** [comment]
![jdk8](https://github.com/user-attachments/assets/d70ed716-cdef-485b-907f-f49ed04c7e8d)

**Comment by wyy0117** [comment]
可能是我这边网络问题，刚刚看又有了，多谢啦。

**Comment by moqsien** [comment]
好用的话，推广，star即可。
